import type { HookScalar } from "@camis/ir-schema";

// PHP files can't carry the TS leading-comment marker (invalid before <?php); place it after <?php.
export const PHP_MARKER = "// @camis:generated — do not edit; regenerated by camis";

export const PHP_TYPE: Record<HookScalar, string> = {
  string: "string",
  text: "string",
  integer: "int",
  float: "float",
  boolean: "bool",
  dateTime: "string",
};
