<?php
// @camis:generated — do not edit; regenerated by camis

declare(strict_types=1);

namespace App\Observers;

use App\Hooks\TransformTitle;
use App\Models\Article;

class ArticleObserver
{
    public function updated(Article $record): void
    {
        if ($record->wasChanged('published_at') && $record->published_at !== null) {
            $out = (new TransformTitle())->run(['title' => $record->title]);
            $record->title = $out['title'];
            $record->saveQuietly();
        }
    }
}
