<?php
// @camis:generated — do not edit; regenerated by camis

declare(strict_types=1);

namespace App\Hooks\Contracts;

interface TransformTitleHook
{
    /**
     * @param array{title: string} $input
     * @return array{title: string}
     */
    public function run(array $input): array;
}
