// Strapi v5 project skeleton templates.
// Captured from a real Strapi 5.48.0 project on 2026-06-16.
// config/database.ts defaults to sqlite; all other configs match Strapi v5 defaults.

export const packageJson = (projectName: string): string =>
  JSON.stringify(
    {
      name: projectName,
      private: true,
      version: "0.1.0",
      description: "Generated by camis",
      scripts: {
        build: "strapi build",
        develop: "strapi develop",
        start: "strapi start",
        strapi: "strapi",
      },
      dependencies: {
        "@strapi/plugin-users-permissions": "5.48.0",
        "@strapi/strapi": "5.48.0",
        "better-sqlite3": "^12.10.0",
        react: "^18.0.0",
        "react-dom": "^18.0.0",
        "react-router-dom": "^6.0.0",
        "styled-components": "^6.0.0",
      },
      devDependencies: {
        "@types/node": "^20",
        typescript: "^5",
      },
      engines: {
        node: ">=18.0.0 <=22.x.x",
      },
    },
    null,
    2,
  );

export const TSCONFIG_JSON = `{
  "compilerOptions": {
    "module": "CommonJS",
    "moduleResolution": "Node",
    "lib": ["ES2020"],
    "target": "ES2019",
    "strict": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "incremental": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "noEmitOnError": true,
    "noImplicitThis": true,
    "outDir": "dist",
    "rootDir": "."
  },
  "include": ["./", "./**/*.ts", "./**/*.js", "src/**/*.json"],
  "exclude": ["node_modules/", "build/", "dist/", ".cache/", ".tmp/", "src/admin/", "**/*.test.*", "src/plugins/**"]
}`;

export const SERVER_TS = `export default ({ env }) => ({
  host: env('HOST', '0.0.0.0'),
  port: env.int('PORT', 1337),
  app: {
    keys: env.array('APP_KEYS'),
  },
  webhooks: {
    populateRelations: env.bool('WEBHOOKS_POPULATE_RELATIONS', false),
  },
});
`;

export const ADMIN_TS = `export default ({ env }) => ({
  auth: {
    secret: env('ADMIN_JWT_SECRET'),
  },
  apiToken: {
    salt: env('API_TOKEN_SALT'),
  },
  transfer: {
    token: {
      salt: env('TRANSFER_TOKEN_SALT'),
    },
  },
  flags: {
    nps: env.bool('FLAG_NPS', true),
    promoteEE: env.bool('FLAG_PROMOTE_EE', true),
  },
});
`;

export const API_TS = `export default {
  rest: {
    defaultLimit: 25,
    maxLimit: 100,
    withCount: true,
  },
};
`;

export const MIDDLEWARES_TS = `export default [
  'strapi::logger',
  'strapi::errors',
  'strapi::security',
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];
`;

export const DATABASE_TS = `import path from 'path';

export default ({ env }) => {
  const client = env('DATABASE_CLIENT', 'sqlite');

  const connections = {
    sqlite: {
      connection: {
        filename: path.join(__dirname, '..', '..', env('DATABASE_FILENAME', '.tmp/data.db')),
      },
      useNullAsDefault: true,
    },
  };

  return {
    connection: {
      client,
      ...connections[client as keyof typeof connections],
      acquireConnectionTimeout: env.int('DATABASE_CONNECTION_TIMEOUT', 60000),
    },
  };
};
`;

export const SRC_INDEX_TS = `export default {
  register() {},
  bootstrap() {},
};
`;

export const ENV = `APP_KEYS=camisDevKeyA,camisDevKeyB
API_TOKEN_SALT=camisDevApiTokenSalt
ADMIN_JWT_SECRET=camisDevAdminJwtSecret
TRANSFER_TOKEN_SALT=camisDevTransferTokenSalt
JWT_SECRET=camisDevJwtSecret
`;

export const PERMISSIONS_INDEX_TS = `import { conditions } from "./permissions/conditions";
import roles from "./permissions/roles.json";

export default {
  async register() {},
  async bootstrap({ strapi }: { strapi: any }) {
    await strapi.admin.services.permission.conditionProvider.registerMany(conditions);
    for (const role of roles) {
      const existing = await strapi.query("admin::role").findOne({ where: { name: role.name } });
      const record = existing ?? (await strapi.query("admin::role").create({ data: { name: role.name, description: role.description } }));
      for (const p of role.permissions) {
        await strapi.query("admin::permission").create({ data: { ...p, role: record.id } });
      }
    }
  },
};
`;
